name: 販売問い合わせ
description: 問い合わせ
title: "<機能>_<事象>_(<キー情報>)"
labels: ["問い合わせ","販売系"]
projects: ["nisnikkeikin/22"]
body:
- type: input
  attributes:
    label: 依頼日
    description: 依頼のあった日づけ。 
  validations:
    required: true
- type: input
  attributes:
    label: 依頼者
  validations:
    required: false
- type: textarea
  attributes:
    label: 問い合わせ内容
    placeholder: |
       なるべく具体的に記載（工事予定)
    value: |
        【内容】
        
  validations:
    required: false
- type: input
  attributes:
    label: 原因
  validations:
    required: false
- type: input
  attributes:
    label: 対応
  validations:
    required: false
- type: input
  attributes:
    label: 横展開
    description: 発生している不具合は他にも同じような不具合が埋め込まれていることが多いです。類似の不具合がないかチェックしましょう。
  validations: 
    required: false
- type: input
  attributes:
    label: 影響調査
    description: 修正を入れるコードがどこから利用されているか。利用されている画面一通りのテストが必要になります。
  validations: 
    required: false
- type: input
  attributes:
    label: 依頼元
    description: 依頼元へのリンクをあったら貼る(Teams等)
  validations:
    required: false
- type: textarea
  attributes:
    label: 関連資料パス
    value: |
    \\nlmnistky01\第１システム\01.【日軽パネルシステム株式会社】\yyyy年度検収物件\運用\yyyymmdd_案件概
    \\nlmnistky01\第１システム\01.【日軽パネルシステム株式会社】\yyyy年度検収物件\運用\yyyymmdd_案件概
    render: markdown
  validations:
    required: false
