name: 販売系_追加要望
description: 追加要望
title: "<機能>_<要望>"
labels: ["追加要望","販売系"]
body:
- type: input
  attributes:
    label: 依頼日
    description: 依頼のあった日づけ
  validations:
    required: true
- type: input
  attributes:
    label: 依頼者
  validations:
    required: false
- type: textarea
  attributes:
    label: 問い合わせ内容
    value: |
        【内容】
        
        
        【工数】
        
  validations:
    required: false
- type: textarea
  attributes:
    label: 関連資料パス
    value: |
         \\nlmnistky01\NisDoc\日軽パネルシステム\00.システム再構築\99.障害対応\1.販売\00000.課題
    render: markdown
  validations:
    required: false
